config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  devise_for :admins

  namespace :user do
    resources :loans, only: [:index, :show, :new, :create, :update]
  end


  namespace :admin do
    resources :loans, only: [:index, :show, :update]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :loans
  validates :email, presence: true, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user
  belongs_to :admin
  has_many :loan_adjustments
  validates :amount, :interest_rate, numericality: { greater_than: 0 }
  validates :status, inclusion: { in: %w[requested approved open closed rejected waiting_for_adjustment_acceptance readjustment_requested] }

  def adjustment_history
    loan_adjustments.map do |adj|
      "Adjusted Amount: #{adj.adjusted_amount}, Adjusted Interest Rate: #{adj.adjusted_interest_rate}"
    end
  end


  def check_loan_repayment
    if user.wallet_balance < amount
      pay_partially
      self.status = 'closed'
      self.save
    end
  end

  def repay_loan
    if user.wallet_balance >= amount
      pay_in_full
    else
      pay_partially
    end
  end

  private

  def pay_partially
    partial_payment = user.wallet_balance
    user.update(wallet_balance: 0)
    admin.update(wallet_balance: admin.wallet_balance + partial_payment)
  end

  def pay_in_full
    user.update(wallet_balance: user.wallet_balance - amount)
    admin.update(wallet_balance: admin.wallet_balance + amount)
  end
end

app/models/loan_adjustment.rb
class LoanAdjustment < ApplicationRecord
  belongs_to :loan
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :loans
  validates :email, presence: true, uniqueness: true
end

app/controllers/admin/loans_controller.rb
class Admin::LoansController < ApplicationController
  before_action :authenticate_admin!

  def update
    @loan = Loan.find(params[:id])
    case params[:commit]
    when 'Approve'
      approve_loan
    when 'Reject'
      reject_loan
    when 'Adjust'
      adjust_loan
    end
  end

  def index
    @loans = Loan.all
  end

  def show
    @loan = Loan.find(params[:id])
  end
  
  private

  def approve_loan
    flash[:notice] = "Loan approved successfully"
    @loan.update(status: 'approved')
    redirect_to admin_loan_path(@loan)
  end

  def reject_loan
    flash[:notice] = "Loan Reject successfully"
    @loan.update(status: 'rejected')
    redirect_to admin_loan_path(@loan)
  end

  def adjust_loan
    @loan.update(status: 'waiting_for_adjustment_acceptance', amount: params[:loan][:amount], interest_rate: params[:loan][:interest_rate])
    LoanAdjustment.create(loan: @loan, adjusted_amount: params[:loan][:amount], adjusted_interest_rate: params[:loan][:interest_rate])
    flash[:notice] = "Loan Adjusted successfully"
    redirect_to admin_loan_path(@loan)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/user/loans_controller.rb
class User::LoansController < ApplicationController
  before_action :authenticate_user!

  def new
    @loan = Loan.new
  end

  def create
    @loan = current_user.loans.new(loan_params.merge(admin: Admin.first, status: 'requested'))
    if @loan.save
      redirect_to user_loans_path, notice: 'Loan requested successfully.'
    else
      render :new
    end
  end

  def show
    @loan = Loan.find(params[:id])
  end

  def index
    @loans = Loan.all
  end

  def update
    @loan = Loan.find(params[:id])
    case params[:commit]
    when 'Accept'
      accept_adjustment
    when 'Reject'
      reject_loan
    when 'Confirm'
      confirm_loan
    when 'Request Readjustment'
      request_readjustment
    when 'Request adjustment'
      request_adjustment
    when 'Repay Loan' 
      repay
    end
  end

  private

  def repay
    @loan = Loan.find(params[:id])
    @loan.repay_loan
    @loan.update(status: 'closed')
    flash[:notice] = "Money tranferred to admin account"
    redirect_to user_loan_path(@loan)
  end

  def confirm_loan
    @loan = Loan.find(params[:id])
    if @loan.status == 'approved'
      if @loan.update(status: 'open')
        current_user.wallet_balance += @loan.amount
        @loan.admin.wallet_balance -= @loan.amount
        if current_user.save && @loan.admin.save
          redirect_to user_loan_path(@loan), notice: 'Loan confirmed and funds transferred to your wallet.'
        else
          redirect_to user_loan_path(@loan), alert: 'Unable to confirm the loan due to wallet update error.'
        end
      else
        redirect_to user_loan_path(@loan), alert: 'Unable to confirm the loan.'
      end
    else
      redirect_to user_loan_path(@loan), alert: 'Loan must be in approved status to confirm.'
    end
  end
  
  def accept_adjustment
    @loan.update(status: 'open')
    update_wallets
    redirect_to user_loan_path(@loan), notice: 'Adjustment Accepted and money transferred to user account'
  end

  def reject_loan
    if @loan.update(status: 'rejected')
      redirect_to user_loans_path, notice: 'Loan rejected successfully.'
    else
      redirect_to user_loan_path(@loan), alert: 'Unable to reject the loan.'
    end
  end

  def request_adjustment
    if @loan.update(status: 'readjustment_requested')
      redirect_to user_loan_path(@loan), notice: 'Loan adjustment request sent to the admin.'
    else
      redirect_to user_loan_path(@loan), alert: 'Unable to request a loan adjustment.'
    end
  end

  def request_readjustment
    @loan.update(status: 'readjustment_requested')
    redirect_to user_loan_path(@loan), notice: 'Readjustment requested successfully'
  end

  def update_wallets
    @loan.user.update(wallet_balance: @loan.user.wallet_balance + @loan.amount)
    @loan.admin.update(wallet_balance: @loan.admin.wallet_balance - @loan.amount)
  end

  def loan_params
    params.require(:loan).permit(:amount, :interest_rate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/loans/_form.html.erb
<%= form_with model: @loan, url: admin_loan_path(@loan), local: true do |f| %>
  <% if @loan.status == 'requested' || @loan.status == 'waiting_for_adjustment_acceptance' || @loan.status == 'readjustment_requested' %>
    <div>
      <%= f.label :amount, 'Loan Amount' %>
      <%= f.text_field :amount %>
    </div>
    <div>
      <%= f.label :interest_rate, 'Interest Rate' %>
      <%= f.text_field :interest_rate %>
    </div>

    <div>
      <%= f.submit 'Approve' %>
      <%= f.submit 'Reject' %>
      <%= f.submit 'Adjust' %>
    </div>
  <% end %>
<% end %>

app/views/admin/loans/index.html.erb
<h1>Admin Wallet Balance: <%= current_admin.wallet_balance %></h1>
<h2>Loan Requests</h2>
<table>
  <tr>
    <th>User</th>
    <th>Amount</th>
    <th>Interest Rate</th>
    <th>Status</th>
    <th>Actions</th>
  </tr>
  <% @loans.each do |loan| %>
    <tr>
      <td><%= loan.user.email %></td>
      <td><%= loan.amount %></td>
      <td><%= loan.interest_rate %></td>
      <td><%= loan.status %></td>
      <td>
        <%= link_to 'View', admin_loan_path(loan) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/loans/show.html.erb
<h1>Admin Wallet: <%= current_admin.wallet_balance %></h1>
<h2>Loan Details</h2>
<p>User: <%= @loan.user.email %></p>
<p>Loan Amount of User with Interest <%= @loan.amount %></p>
<p>Interest Rate: <%= @loan.interest_rate %></p>
<p>Status: <%= @loan.status %></p>

<%= render 'form', loan: @loan %>
<%= link_to "Go to User", user_loan_path(@loan)%> |
<% if current_admin %>
  <%= button_to "Sign out", destroy_admin_session_path, method: :delete %>
<%end%>

app/views/home/_navigation.html.erb
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
<%= link_to "Lending Money System", root_path, class: "navbar-brand"  %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

</div>

app/views/home/index.html.erb
<h2>Lending Money System</h2>
<% if user_signed_in? %> 
 <div> Welcome <%= current_user.email %> </div>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
  <%= button_to "Admin Sign in", new_admin_session_path %>
<% elsif admin_signed_in? %>
  <div> Welcome <%= current_admin.email %> </div>
  <%= button_to "Sign out", destroy_admin_session_path, method: :delete %>
  <%= button_to "User Sign in", new_user_session_path %>
<% else %>
  <%= button_to "User Sign in", new_user_session_path %>
  <%= button_to "Admin Sign in", new_admin_session_path %>
<%end%>
<% if current_user %>
  <%= link_to "Request New Loan", new_user_loan_path%> | 
  <%= link_to "Your All Loans Details", user_loans_path%>
<%end%>
<% if current_admin %>
  <%= link_to "Users Loans Details", admin_loans_path%>
<%end%>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin Dashboard</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>
  <h1>Admin Dashboard</h1>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LendingMoneyWithIntrest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>User Dashboard</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>
  <h1>User Dashboard</h1>
  <%= yield %>
</body>
</html>

app/views/user/loans/_form.html.erb
<%= form_with model: @loan, url: user_loan_path(@loan), local: true do |f| %>
  <% if @loan.status == 'approved' %>
    <div>
      <%= f.submit 'Confirm' %>
      <%= f.submit 'Reject' %>
    </div>
  <% elsif @loan.status == 'waiting_for_adjustment_acceptance' %>
    <div>
      <%= f.submit 'Accept' %>
      <%= f.submit 'Reject' %>
      <%= f.submit 'Request Readjustment' %>
    </div>
  <% end %>
<% end %>

app/views/user/loans/index.html.erb
<h1>User Wallet:<%= current_user.wallet_balance %></h1>
<h2>Your Loans</h2>
<table>
  <tr>
    <th>Amount</th>
    <th>Interest Rate</th>
    <th>Status</th>
    <th>Actions</th>
  </tr>
  <% @loans.each do |loan| %>
    <tr>
      <td><%= loan.amount %></td>
      <td><%= loan.interest_rate %></td>
      <td><%= loan.status %></td>
      <td>
        <%= link_to 'View', user_loan_path(loan) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/user/loans/new.html.erb
<h2>Request a New Loan</h2>
<%= form_with model: @loan, url: user_loans_path, local: true do |f| %>
  <div>
    <%= f.label :amount, 'Loan Amount' %>
    <%= f.text_field :amount %>
  </div>
  <div>
    <%= f.label :interest_rate, 'Interest Rate' %>
    <%= f.text_field :interest_rate %>
  </div>

  <div>
    <%= f.submit 'Request Loan' %>
  </div>
<% end %>

app/views/user/loans/show.html.erb
<h1>User Wallet:<%= current_user.wallet_balance %></h1>
<h2>Loan Details</h2>
<p>Total Loan Amount with Interest: <%= @loan.amount %></p>
<p>Wallet Balance: <%= @loan.user.wallet_balance %></p>
<p>Interest Rate: <%= @loan.interest_rate %></p>
<p>Status: <%= @loan.status %></p>
<% if @loan.status == 'approved' || @loan.status == 'waiting_for_adjustment_acceptance' %>
  <%= render 'form', loan: @loan %>
<% elsif @loan.status == 'open' %>
  <%= form_with model: @loan, url: user_loan_path(@loan), local: true do |f| %>
          <%= f.submit 'Repay Loan' %>
  <%end%>
<% end %>
| <%= link_to "Go to Admin", admin_loan_path(@loan) if current_admin %> |
<%= link_to "Your all loans", user_loans_path %> |
<%= link_to "Rquest New Loan", new_user_loan_path %> |
<% if current_user %>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<%end%>